import {
  Box,
  Center,
  Text,
  VStack,
  FormLabel,
  FormControl,
  Input,
  Button,
  Flex,
} from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { Logo } from "../components/common/iconos";
import { Login, sessionChange } from "../firebase/services/auth";

export default function Home() {
  const [error, setError] = useState("");
  const [adminSession, setAdminSession] = useState("");

  const router = useRouter();

  useEffect(() => {
    sessionChange(setAdminSession);
  }, [adminSession]);

  useEffect(() => {
    adminSession && router.replace("/dashboard");
  }, [adminSession]);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();

  return (
    <div>
      <Head>
        <title>mmChokers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h={"100vh"} justify={"center"} align={"center"} p={"30px 20px"}>
        <form>
          <Box m={"60px"}>
            <Logo />
          </Box>
          <VStack spacing={5} w={{ base: "100%", tablet: "400px" }}>
            <FormControl>
              <FormLabel color={"#000"} mt="10px">
                Email
              </FormLabel>
              <Input
                id="loginEmail"
                type={"email"}
                w={"100%"}
                color={"#000"}
                placeholder="asd123@gmail.com"
                bg={"#fff"}
                {...register("email")}
              />
            </FormControl>

            <FormControl>
              <FormLabel color={"#000"} mt="10px">
                Contraseña
              </FormLabel>
              <Input
                id="loginPassword"
                type={"password"}
                w={"100%"}
                bg={"#fff"}
                color={"#000"}
                placeholder="Contraseña"
                {...register("password")}
              />
            </FormControl>

            <Button
              onClick={handleSubmit((data) => {
                Login(data, setError);
              })}
              w="full"
              variant={"primary"}
            >
              Iniciar Sesion
            </Button>
            <Box h="50px">
              {error && <Text color={"red.400"}>{error}</Text>}
            </Box>
          </VStack>
        </form>
      </Flex>
    </div>
  );
}
